import type { Metadata } from "next";
import localFont from "next/font/local";
import "@/styles/globals.css";
import Footer from "./components/Footer/Footer";
import Header from "./components/Header/Header";
import Hero from "./components/Hero/Hero";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="antialiased">
            <Header />
            <Hero />

            {children}

            <Footer />
      </body>
    </html>
  );
}
